spring:
#  thymeleaf:
#    mode: HTML5
#    cache: false
  datasource:
    url: jdbc:mysql://101.37.14.131:3306/blog?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Smash_2019
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true


#logging:
#  level:
#    root: warn
#    com.wwh: info
#  file: log/blog-pro.log

server:
  port: 8081
