spring:
#  thymeleaf:
#    mode: HTML5
#    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/studio?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true


logging:
  level:
    root: info
    com.wwh: debug
  file: log/blog-dev.log
